version: '3.8'

services:
  postgres:
    image: postgres:16.6
    container_name: postgres_db
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: pr0y3ct_ñ
      POSTGRES_DB: proyecto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volumen persistente para los datos de PostgreSQL
      - ./db/init.sql:/docker-entrypoint-initdb.d/query.sql
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jota.gvg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pr0y3ct
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Volumen persistente para los datos de pgAdmin
    depends_on:
      - postgres
    networks:
      - app_network

  api:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229" # Debugging con --inspect
    volumes:
      - .:/app
      - /app/node_modules # Evita conflictos con dependencias locales
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - app_network
    command: npm run dev

volumes:
  postgres_data: # Volumen persistente para PostgreSQL
  pgadmin_data:
    # Volumen persistente para pgAdmin

networks:
  app_network:
    driver: bridge
